### ISSUE TITLE
new update breaks workspaces

### ISSUE THREAD

**Issue by ElequacityYT** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#104]
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/139906201/2dfb0e50-7ad4-4758-8f00-bb5b185f1b74)
it shows this when you load a workspace with the plugin installed
this is on forge 1.20.1
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/139906201/784c3ba4-97ee-4a5c-a66b-1876c27ef7fb)

**Comment by MagicalAlexey** [comment]
I confirm (this break all workspace on 1.20.1)

**Comment by MateusKH** [comment]
It's the same thing with me, breaking gradle in the plugin.

**Comment by SpiderMenaceYT** [comment]
it's also breaking the gradle in mine as well.

**Comment by kokancursedtv** [comment]
Same happened me too.

**Comment by NerdyPuzzle** [comment]
![Screenshot_2024-04-14-07-07-08-65_fc90557b4939f0bdf6f556efb0a965c9.jpg](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/8d8ba727-bb83-4697-8932-3fc199f5686a)

Everything works fine for me after clearing all my gradle caches, are you sure it's caused by the plugin?

**Comment by NerdyPuzzle** [comment]
Try the second most common solution in
 https://mcreator.net/wiki/gradle-setup-errors

**Comment by NerdyPuzzle** [comment]
This does not seem related to the geckolib plugin but broken gradle caches instead since my 1.20.1 workspace is working just file. Will mark as invalid unless it's proven that geckolib is the issue.

**Comment by NerdyPuzzle** [comment]
![Screenshot_2024-04-14-07-27-02-39_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/23aa750e-217e-4848-b63c-0e18c0ac77a0)

![Screenshot_2024-04-14-07-24-06-61_cbf47468f7ecfbd8ebcc46bf9cc626da.jpg](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/ad88834e-1a1a-43bc-a390-df9aa5cea485)

Following these 2 steps should fix any gradle issues you have, as other people I helped had them work. I repeat, this is not caused by geckolib, but by gradle on its own acting up.

**Comment by NerdyPuzzle** [comment]
@MagicalAlexey @kokancursedtv @MateusKH @SpiderMenaceYT @ElequacityYT refer to the above comment

**Comment by largehammer3** [comment]
got this message while using the latest version (just redownloaded 5 minutes ago), could this possibly be related?
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/151718249/cbda02fa-b202-4cd7-96a9-9bb72c8f1ea7)

**Comment by NerdyPuzzle** [comment]
No, this is a different issue
