### ISSUE TITLE
Can't stop looping block animations

### ISSUE THREAD

**Issue by AlexDerProGamer** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#36]
I used NBT Number Tags but Minecraft won't stop the animation. I tried 2 Procedures. The block even saves the Number Tag (/data get block) but the animation goes on forever. I don't know if it's a bug or I'm just to dumb.

### First procedure (when I right click the block):
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/111710468/9d92fb1e-bdb7-4fa1-87d6-57f32a13c668)

### Second procedure (block update tick (ticking is enabled)):
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/111710468/bf8e7116-def2-4336-8d75-82795c732f65)

I really don't know what to do...
Sorry for annoying you

**Comment by miventech** [comment]
I have the same problem once I change the animation, to another I can't change it or rewrite it

**Comment by miventech** [comment]
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/68956835/c866e0bc-5828-40cb-a239-543ce86fb516)

The only way I found to stop the animation was to replace the block by itself and keep the NBT tags but not the state although it only works when I'm in the UI, because when I try to do it via a Tick update it doesn't work....
