### ISSUE TITLE
Minecraft refuses to launch after creating animated entity

### ISSUE THREAD

**Issue by justonething1thing** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#65]
Hi!

I've followed the text tutorial to the best of my ability, followed three different videos including one in spanish, and still can't get minecraft to launch after creating an animated entity. Tried switching to creating for 1.19 after seeing that the 1.20 version can cause bugs, pretty sure it's the correct version of the plugin, changing the animation labels in blockbench, exporting each animation individually vs as a grouped together file, creating a procedure to tell mcreator to play the animations (even though they still fall under the preset slots available and creating procedures was only for extra animations not listed as a preset, according to the text tutorial), what animation file names I'm pointing mcreator to in the preset idle and walk options. A parent trying to figure this out for a kiddo, but obviously I'm missing something. Fresh set of eyes would be super helpful. Have attached the error message I manged to get the one time it DID load anything at all, as well as the blockbench setup when I got that.

![Screenshot (690)](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/61524341/02de49cc-caab-4916-966c-8b7a48ee0aec)
![Screenshot (691)](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/61524341/d1395e2f-f9e4-43ff-8289-e1f02b41b173)

**Comment by NerdyPuzzle** [comment]
Not sure why that happens for you. If you send a download to a copy of your workspace I can take a look once I'm free this Tuesday.

**Comment by NerdyPuzzle** [comment]
I downloaded your workspace and tested it. It did end up compiling fine, though it _did_ crash once I tried running the game. That was due to your animation file being a little broken, but I fixed it for you; here it is. 

[ostrich.animation.json](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/files/13293688/ostrich.animation.json)

Just reimport the model with this and it will work fine. If you're still getting a compilation error, click the bandage icon next to the run button. 
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/df6835ec-98c3-4224-b03e-e4227cfcf430)

Just make sure you have the plugin version 4.8.9 and have no conflicting plugins such as other geckolib plugins not made by me.

**Comment by NerdyPuzzle** [comment]
Also you might notice the animations won't play on the entity, that's because you wrote the wrong animation names in the entity.
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/9aa4d622-cad9-4074-9902-3f21739a7505)
![image](https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/assets/112079900/bcc436f3-7130-4f8a-9059-3bbef08449ad)

**Comment by justonething1thing** [comment]
OH MY GOODNESS it worked, oh my gosh thank you so much my son is going to flip out I'm so excited! Thank you!!!!! Do you happen to remember what I was doing wrong with the animations themselves? Going to fix that going forward and making sure my file names and animation names match up properly and hoping to rock this! :D

**Comment by NerdyPuzzle** [comment]
I don't know why exactly the animation files sometimes get messed up, but It's something going on with blockbench formatting. I just finished writing a windows application today that automatically fixes all the animations in a workspace if they happen to have issues with their formatting. If something like this happen again you can try using it https://www.mediafire.com/file/urrv45s50bioow4/GeckoLib_animation_fixer.exe/file

**Comment by justonething1thing** [comment]
Thank you so much!!! Appreciate all the work you've put into this tool, topic, and the plugin in general. :)
